// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PXJBgPMwl05ffhOhiSBVAA-NayQisAw',
    appId: '1:783492120129:web:3e8824964e8420d22290c0',
    messagingSenderId: '783492120129',
    projectId: 'wiredmaps-a4536',
    authDomain: 'wiredmaps-a4536.firebaseapp.com',
    storageBucket: 'wiredmaps-a4536.appspot.com',
    measurementId: 'G-014SYGBX2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYrZ8khNzY9bGt3sYNPyQPo9Qwim0gsY',
    appId: '1:783492120129:android:d78cd59ace2791a42290c0',
    messagingSenderId: '783492120129',
    projectId: 'wiredmaps-a4536',
    storageBucket: 'wiredmaps-a4536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpXstAsdhb9r3aotUvcts87PJfRVcXZs',
    appId: '1:783492120129:ios:7f740d26e33034832290c0',
    messagingSenderId: '783492120129',
    projectId: 'wiredmaps-a4536',
    storageBucket: 'wiredmaps-a4536.appspot.com',
    iosClientId: '783492120129-qfk3ln5nr6rak18961tilh33rs2dvrr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpXstAsdhb9r3aotUvcts87PJfRVcXZs',
    appId: '1:783492120129:ios:7f740d26e33034832290c0',
    messagingSenderId: '783492120129',
    projectId: 'wiredmaps-a4536',
    storageBucket: 'wiredmaps-a4536.appspot.com',
    iosClientId: '783492120129-qfk3ln5nr6rak18961tilh33rs2dvrr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carApp',
  );
}
